# Generated by Django 2.2.2 on 2020-02-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_delete_dnt'),
    ]

    operations = [
        migrations.CreateModel(
            name='dnt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dnt_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='dmt',
            old_name='dnt_name',
            new_name='dmt_name',
        ),
        migrations.RemoveField(
            model_name='dmt',
            name='sms_received',
        ),
        migrations.RemoveField(
            model_name='dmt',
            name='sms_sent',
        ),
        migrations.RemoveField(
            model_name='user_request',
            name='sms',
        ),
        migrations.RemoveField(
            model_name='user_request',
            name='sos',
        ),
    ]
