# Generated by Django 2.2.2 on 2020-02-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200216_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmt',
            name='dmt_account_sid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dmt',
            name='dmt_auth_token',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dnt',
            name='dnt_account_sid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dnt',
            name='dnt_auth_token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
